# Generated by Django 3.1 on 2020-08-09 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceSemantic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1000)),
                ('flag', models.BooleanField(default=0)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20000), blank=True, size=None)),
                ('username', models.CharField(max_length=25)),
            ],
        ),
    ]
