# Generated by Django 3.1 on 2020-08-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordSemantic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentenceSemantic',
            new_name='WordSemantic',
        ),
    ]
