# Generated by Django 3.1 on 2020-08-09 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordSemantic', '0002_auto_20200809_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsemantic',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
