# Generated by Django 3.1 on 2020-08-09 13:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordSemantic', '0003_auto_20200809_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsemantic',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='wordsemantic',
            name='sentence',
            field=models.CharField(max_length=100000),
        ),
    ]
