# Generated by Django 3.1 on 2020-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentencesemantic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencesemantic',
            name='labels',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sentencesemantic',
            name='sentence',
            field=models.CharField(max_length=100000),
        ),
    ]
