# Generated by Django 3.1 on 2020-08-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLabel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
