# Generated by Django 3.1 on 2020-08-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='none@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
