# Generated by Django 3.1 on 2020-08-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiorecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=100000),
        ),
    ]
